export const defaultCategories = [
  {
    legacyId: 'cat_kahvalti',
    name: 'Kahvaltı',
    nameEn: 'Breakfast',
    description: 'Güne başlangıç tabakları.',
    descriptionEn: 'Plates to start the day.',
    sortOrder: 1,
  },
  {
    legacyId: 'cat_baslangic',
    name: 'Başlangıçlar',
    nameEn: 'Starters',
    description: 'Paylaşımlık ve küçük porsiyonlar.',
    descriptionEn: 'Shared plates and small portions.',
    sortOrder: 2,
  },
  {
    legacyId: 'cat_ana',
    name: 'Ana Yemekler',
    nameEn: 'Mains',
    description: 'Izgara, güveç ve ana tabaklar.',
    descriptionEn: 'Grills, stews, and main plates.',
    sortOrder: 3,
  },
  {
    legacyId: 'cat_burger',
    name: 'Burger',
    nameEn: 'Burgers',
    description: 'El yapımı burgerler.',
    descriptionEn: 'House-made burgers.',
    sortOrder: 4,
  },
  {
    legacyId: 'cat_pizza',
    name: 'Pizza',
    nameEn: 'Pizza',
    description: 'Taş fırın pizzalar.',
    descriptionEn: 'Stone-baked pizzas.',
    sortOrder: 5,
  },
  {
    legacyId: 'cat_makarna',
    name: 'Makarna',
    nameEn: 'Pasta',
    description: 'Taze makarnalar.',
    descriptionEn: 'Fresh pasta.',
    sortOrder: 6,
  },
  {
    legacyId: 'cat_tatli',
    name: 'Tatlı',
    nameEn: 'Desserts',
    description: 'Günlük tatlılar.',
    descriptionEn: 'Daily desserts.',
    sortOrder: 7,
  },
  {
    legacyId: 'cat_kahve',
    name: 'Kahve',
    nameEn: 'Coffee',
    description: 'Espresso bazlı kahveler.',
    descriptionEn: 'Espresso-based coffees.',
    sortOrder: 8,
  },
  {
    legacyId: 'cat_soguk',
    name: 'Soğuk İçecekler',
    nameEn: 'Cold drinks',
    description: 'Serinletici içecekler.',
    descriptionEn: 'Cold drinks.',
    sortOrder: 9,
  },
  {
    legacyId: 'cat_sicak',
    name: 'Sıcak İçecekler',
    nameEn: 'Hot drinks',
    description: 'Çay ve sıcak içecekler.',
    descriptionEn: 'Tea and hot drinks.',
    sortOrder: 10,
  },
]
